---
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: Title
  default: Ethertoxicus Malidictus
- name: sub_heading
  label: Sub Heading
  type: text
  hidden: false
  default: Singularity... welcome digital overlords!
- name: banner_image
  label: Banner Image
  type: file
  description: Dimensions work best at 1200 pixels by 400 pixels
  hidden: false
  default: "/uploads/2018/02/17/neurons.jpg"
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
